import tweepy

TWITTER_API_KEY = "cahicoWKXdrcx0kMcWmrkzGgY"
TWITTER_API_SECRET_KEY = "Mam8ZoSVhsU3L6lqJ5S0EhK4vbyj2BWYMELgSNDMKR2cADxlpr"
TWITTER_ACCESS_TOKEN = "1675423387-Kp0NxfF4jquYovDmppptmbtU4HW85VXq0L9i7JF"
TWITTER_ACCESS_TOKEN_SECRET = "3CF0Vr66XZrablKqzNIcEAs78trdSiooqUWd0ATZ25lt7"

auth = tweepy.OAuthHandler(TWITTER_API_KEY, TWITTER_API_SECRET_KEY)
auth.set_access_token(TWITTER_ACCESS_TOKEN, TWITTER_ACCESS_TOKEN_SECRET)

api = tweepy.API(auth)